#!/usr/bin/env coffee

import {minify} from 'html-minifier-terser'
import {root} from './dir'
import {join} from 'path'
import {writeFileSync,readFileSync} from 'fs'

dir = join root,'site/.vuepress/dist'
page404 = join dir,'404.html'

html = readFileSync page404,'utf8'
html = html.replace('<!--[--><404></404><!--]-->','')

html = await minify(
  html
  includeAutoGeneratedTags: true
  removeAttributeQuotes: true
  removeComments: true
  removeRedundantAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  sortClassName: true
  useShortDoctype: true
  collapseWhitespace: true
)

writeFileSync page404, html

begin = html.indexOf('id=app')
begin = html.indexOf(">",begin)
end = html.lastIndexOf('<script')


writeFileSync(
  join(dir,"index.html")
  html[..begin]+"</div>"+html[end..]
)
